# Generated by Django 2.1.1 on 2018-10-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applist',
            name='imgurl',
            field=models.ImageField(upload_to='images/app', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='OtherMsg',
            field=models.CharField(max_length=300, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='imgurl',
            field=models.ImageField(upload_to='images/post', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='msg',
            field=models.CharField(max_length=300, verbose_name='文章信息'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='标题'),
        ),
    ]
