# Generated by Django 2.1.1 on 2018-10-20 07:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applist',
            name='LANdomurl',
        ),
        migrations.AddField(
            model_name='applist',
            name='PANdomurl',
            field=models.CharField(default=datetime.datetime(2018, 10, 20, 7, 37, 13, 453898, tzinfo=utc), max_length=300, verbose_name='软件地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applist',
            name='WANdomurl',
            field=models.CharField(max_length=300, verbose_name='软件地址'),
        ),
        migrations.AlterField(
            model_name='applist',
            name='imgurl',
            field=models.ImageField(upload_to='static/images', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='applist',
            name='msg',
            field=models.CharField(max_length=300, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='applist',
            name='title',
            field=models.CharField(max_length=10, unique=True, verbose_name='标题'),
        ),
    ]
