# Generated by Django 2.0.7 on 2018-12-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applist',
            name='PANdomurl',
        ),
        migrations.RemoveField(
            model_name='applist',
            name='WANdomurl',
        ),
        migrations.RemoveField(
            model_name='applist',
            name='msg',
        ),
        migrations.AlterField(
            model_name='applist',
            name='imgurl',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='imgurl',
            field=models.ImageField(upload_to='static_collected/images/PhotoWall', verbose_name='图片地址'),
        ),
    ]
