# Generated by Django 2.0.7 on 2018-12-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0002_auto_20181207_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='applist',
            name='PANdomurl',
            field=models.CharField(default=1, max_length=300, verbose_name='文件地址'),
            preserve_default=False,
        ),
    ]
