# Generated by Django 2.1.1 on 2018-11-10 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0002_auto_20181110_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='标题')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
                ('isDelete', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name_plural': '文章类型',
            },
        ),
        migrations.AddField(
            model_name='dynamic',
            name='TitleClassificationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeApp.TitleClassification', verbose_name='文章类型'),
        ),
    ]
