# Generated by Django 2.1.1 on 2018-10-27 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_titleclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='TitleClassificationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeApp.TitleClassification', verbose_name='文章类型'),
        ),
    ]
