# Generated by Django 2.0.7 on 2018-12-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_applist_pandomurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='applist',
            name='Appclass',
            field=models.CharField(choices=[('常用', 'do1'), ('娱乐', 'do2')], default=1, max_length=30, verbose_name='性别'),
            preserve_default=False,
        ),
    ]
