# Generated by Django 2.1.1 on 2018-11-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_auto_20181110_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamic',
            old_name='TitleClassificationID',
            new_name='Classid',
        ),
    ]
