# Generated by Django 2.1.1 on 2018-10-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0004_dynamic_titleclassificationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='TitleClassificationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.TitleClassification', verbose_name='文章类型'),
        ),
    ]
