# Generated by Django 2.0.7 on 2018-12-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0004_applist_appclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applist',
            name='Appclass',
            field=models.CharField(choices=[('do1', '常用'), ('do2', '娱乐'), ('do3', '其他')], max_length=30, verbose_name='类别'),
        ),
    ]
