# Generated by Django 2.1.1 on 2018-11-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0004_auto_20181110_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoWall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Myname', models.CharField(max_length=100, unique=True, verbose_name='姓名')),
                ('imgurl', models.ImageField(upload_to='static/images/PhotoWall', verbose_name='图片地址')),
                ('msg', models.CharField(max_length=300, verbose_name='简介')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
                ('isDelete', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name_plural': '照片墙',
            },
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('numbers', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('imgurl', models.ImageField(upload_to='static/images/PhotoWall', verbose_name='图片地址')),
                ('msg', models.CharField(max_length=300, verbose_name='简介')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
                ('isDelete', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name_plural': '社团物品',
            },
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='Classid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HomeApp.TitleClassification', verbose_name='文章类型'),
            preserve_default=False,
        ),
    ]
