# Generated by Django 2.1.1 on 2018-11-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='单位')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
                ('isDelete', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='User_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=30, verbose_name='性别')),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='经验')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
                ('isDelete', models.BooleanField(default=True, verbose_name='是否可用')),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Unit_class', verbose_name='班级')),
            ],
            options={
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='UsPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名(默认不填)')),
                ('imgurl', models.ImageField(upload_to='static/images/UserPicture', verbose_name='图片地址')),
                ('motto', models.CharField(max_length=100, verbose_name='格言')),
                ('msg', models.CharField(max_length=300, verbose_name='简介')),
                ('LoveColor', models.CharField(choices=[('Red', '红色'), ('Pink', '粉红色'), ('Purple', '紫色'), ('Deep-Purple', '深紫色'), ('Indigo', '靛蓝'), ('Blue', '蓝色')], max_length=30, verbose_name='颜色')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
                ('isDelete', models.BooleanField(default=True, verbose_name='是否可用：')),
                ('UserID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.User_Information', verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '成员个性签名',
            },
        ),
    ]
