# Generated by Django 2.0.7 on 2018-12-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
            ],
            options={
                'verbose_name_plural': '签到日志',
            },
        ),
        migrations.RemoveField(
            model_name='user_information',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user_information',
            name='ClassID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.Unit_class', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='user_sign',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.User_Information', verbose_name='姓名'),
        ),
    ]
