# Generated by Django 2.0.7 on 2018-12-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20181208_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_sign',
            name='isDelete',
            field=models.BooleanField(default=True, verbose_name='是否可用'),
        ),
    ]
