# Generated by Django 2.1.1 on 2018-11-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20181110_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_picture',
            new_name='Userpicture',
        ),
    ]
