# Generated by Django 2.1.1 on 2018-11-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_remove_uspicture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uspicture',
            name='name',
            field=models.CharField(default=1, max_length=30, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
