# Generated by Django 2.1.1 on 2018-11-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20181110_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpicture',
            name='gender',
            field=models.CharField(choices=[('Red', 'Red'), ('Pink', 'Pink')], default=1, max_length=30, verbose_name='颜色'),
            preserve_default=False,
        ),
    ]
