# Generated by Django 2.1.1 on 2018-11-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_userpicture_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpicture',
            name='gender',
        ),
        migrations.AddField(
            model_name='userpicture',
            name='LoveColor',
            field=models.CharField(choices=[('Red', '红色'), ('Pink', 'Pink')], default=1, max_length=30, verbose_name='颜色'),
            preserve_default=False,
        ),
    ]
